#Main settings

title: /// Piotr Adamus ///
author:
  name: Piotr Adamus
  email: "PanPiotrAdamus@gmail.com"
description: >
  Super, awesome and what not :)
  Mostly about Python, Treasury, some VBA and other random stuff.
timezone: Europe/Amsterdam
url: "https://PanPiotrAdamus.github.io"

# Build settings

markdown: kramdown

kramdown:
  syntax_highlighter: rouge

theme: minima
minima:
  skin: solarized 
  social_links:
    linkedin: Piotr-Adamus
    github: PanPiotrAdamus

plugins:
  - jekyll-feed
  - jekyll-sitemap
