#Main settings

title: /// Piotr Adamus ///
email: "PanPiotrAdamus@gmail.com"
description: >
  Super, awesome and what not :)
  Mostly about Python, Treasury, some VBA and other random stuff.
timezone: Europe/Amsterdam
url: "https://PanPiotrAdamus.github.io"

# Build settings

markdown: kramdown

kramdown:
  syntax_highlighter: rouge

theme: minima
linkedin_username: Piotr-Adamus
github_username: PanPiotrAdamus

plugins:
  - jekyll-feed
  - jekyll-sitemap
