#Main settings

title: /// Piotr Adamus ///
email: "PanPiotrAdamus@gmail.com"
description: >
  Python, JupyterLab, Altair, VBA, OpenSCAD, SQL, shell(s), RunBSD, Finance ...
timezone: Europe/Amsterdam
url: "https://PanPiotrAdamus.github.io"

# Build settings

markdown: kramdown

kramdown:
  syntax_highlighter: rouge

theme: minima

header_pages:
  - about.markdown
  - tagpage.markdown
  - tagpage.html

linkedin_username: Piotr-Adamus
github_username: PanPiotrAdamus

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
